export const grants = [
  {
    id: "001",
    created_at: "2026-01-12",
    title: "Edital Cultura SP",
    state_scope: "SP",
    area: "Cultura",
    opening_date: "2026-01-01",
    closing_date: "2026-03-30",
    total_value: "R$ 500.000",
    value_per_project: "R$ 50.000",
    source: "Secretaria de Cultura",
    source_url: "https://www.exemplo.com/edital-cultura-sp",
    sender_name: "Ana Ribeiro",
    raw_text:
      "Edital para projetos culturais no estado de São Paulo. Inscrições abertas até 30/03/2026.",
    notes: "Verificar se a Terra 7 pode inscrever projeto de formação.",
  },
  {
    id: "002",
    created_at: "2026-01-14",
    title: "Fomento Artes Visuais",
    state_scope: "RJ",
    area: "Cultura",
    opening_date: "2026-01-10",
    closing_date: "2026-04-10",
    total_value: "R$ 300.000",
    value_per_project: "R$ 30.000",
    source: "Instituto Cultural",
    source_url: null,
    sender_name: "Carlos Mendes",
    raw_text: "Oportunidade para artistas e coletivos de artes visuais.",
    notes: "",
  },
  {
    id: "003",
    created_at: "2026-01-18",
    title: "Edital Juventude Criativa",
    state_scope: "BA",
    area: "Juventude",
    opening_date: "2026-01-05",
    closing_date: "2026-04-20",
    total_value: "R$ 200.000",
    value_per_project: "R$ 20.000",
    source: "Fundação Jovem",
    source_url: null,
    sender_name: "Mariana Lopes",
    raw_text: "Edital voltado a iniciativas de juventude e inovação social.",
    notes: "",
  },
];